import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppShell from "./component/AppShell";
import { CartProvider } from "./component/shared/Cartcontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html
  lang="en"
  suppressHydrationWarning
  className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
>
  <body suppressHydrationWarning className="min-h-full flex flex-col">
    <CartProvider>
      <AppShell>{children}</AppShell>
    </CartProvider>
  </body>
</html>
  );
}
